// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPpXjQcj2xdTqfCvlBLCLgmRYacrWjupU',
    appId: '1:1068511233454:web:575d437de3c7b4a3a6f43f',
    messagingSenderId: '1068511233454',
    projectId: 'flutter-app-template-dev',
    authDomain: 'flutter-app-template-dev.firebaseapp.com',
    storageBucket: 'flutter-app-template-dev.appspot.com',
    measurementId: 'G-8NN8E414GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDISVeIZxN9GYCMqLAYUD4et5RGtm34igw',
    appId: '1:117552215653:android:4ee5fb1c617702246fb88c',
    messagingSenderId: '117552215653',
    projectId: 'someapp-dev-dfa74',
    storageBucket: 'someapp-dev-dfa74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1tQtyju6RFuhJ3B28-m5ccfVihxQ6-5s',
    appId: '1:117552215653:ios:859e132562030e3d6fb88c',
    messagingSenderId: '117552215653',
    projectId: 'someapp-dev-dfa74',
    storageBucket: 'someapp-dev-dfa74.appspot.com',
    androidClientId: '117552215653-87n8j34nldj8tk7tjdcmunl1fbbrrt1i.apps.googleusercontent.com',
    iosClientId: '117552215653-5dqqqgp7joq7t8urcl7vcogr8ualelr4.apps.googleusercontent.com',
    iosBundleId: 'com.u1206yaya.FlutterAppTemplate.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3qF31ymtLr6G6T7vNtb0O3LVrZnZRVCY',
    appId: '1:1068511233454:ios:0fbb2ad807bb95dda6f43f',
    messagingSenderId: '1068511233454',
    projectId: 'flutter-app-template-dev',
    storageBucket: 'flutter-app-template-dev.appspot.com',
    iosClientId:
        '1068511233454-jqkcgldo7cro8bsap1j574959nmgfjqe.apps.googleusercontent.com',
    iosBundleId: 'com.u1206yaya.FlutterAppTemplate.dev',
  );
}